# **Pytorch Tutorial**


In [2]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [13]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-1.6021, -0.5747, -0.0694,  0.0282, -2.1286],
        [-1.5798, -0.2866,  0.2294,  1.1620, -0.9151],
        [ 1.2771, -2.3904, -0.5044, -0.4194, -0.7016],
        [-1.6060,  1.5389,  1.6723,  0.8614, -0.3028]])
tensor([[-0.5184,  1.7938, -0.8264,  0.5381, -1.1189],
        [-0.5438, -1.2052,  0.2463, -0.2001, -0.5645],
        [ 1.6185, -0.0455, -0.3182, -0.0081,  1.2430],
        [ 2.0331,  1.0308, -0.2316,  3.2280,  1.2893]])
tensor([[ 0.5088,  0.3974, -0.0618,  0.8999,  0.6564],
        [-0.6711, -1.3057, -0.3199,  0.5936,  0.8078],
        [ 2.1190,  0.0718, -0.0356, -1.6012, -0.1730],
        [ 0.3459, -0.4091,  0.4327,  0.7132,  0.2091]])


In [14]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.6723)


In [15]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([ 1.2771,  1.5389,  1.6723,  1.1620, -0.3028])
tensor([2, 3, 3, 1, 3])


In [16]:
# 2-2
# 显式地写出了参数名
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([ 1.2771,  1.5389,  1.6723,  1.1620, -0.3028])
tensor([2, 3, 3, 1, 3])


In [17]:
# 2-3
# false对用keepdim参数，默认，即压缩掉被操作的维度
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([ 1.2771,  1.5389,  1.6723,  1.1620, -0.3028])
tensor([2, 3, 3, 1, 3])


举个例子说明keepdim

In [18]:
x1 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # shape = (2, 3)
m1, idx1 = torch.max(x1, 0, False)  # keepdim=False
print('keepdim=false, m1=' , m1)  # tensor([4, 5, 6]) shape = (3,)
print('keepdim=false, m1.shape=' , m1.shape)
print('keepdim=false, idx1=' , idx1)  # tensor([1, 1, 1]) shape = (3,)
print('keepdim=false, idx1.shape=', idx1.shape)
# 当keepdim=true
m2, idx2 = torch.max(x1, 0, True)  # keepdim=True
print('keepdim=true, m2=' , m2)  # tensor([[4, 5, 6]]) shape = (1, 3)
print('keepdim=true, m2.shape=' , m2.shape)
print('keepdim=true, idx2=' , idx2)  # tensor([[1, 1, 1]]) shape = (1, 3)
print('keepdim=true, idx2.shape=', idx2.shape)

keepdim=false, m1= tensor([4, 5, 6])
keepdim=false, m1.shape= torch.Size([3])
keepdim=false, idx1= tensor([1, 1, 1])
keepdim=false, idx1.shape= torch.Size([3])
keepdim=true, m2= tensor([[4, 5, 6]])
keepdim=true, m2.shape= torch.Size([1, 3])
keepdim=true, idx2= tensor([[1, 1, 1]])
keepdim=true, idx2.shape= torch.Size([1, 3])


In [19]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[ 1.2771,  1.5389,  1.6723,  1.1620, -0.3028]])
tensor([[2, 3, 3, 1, 3]])


In [20]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([ 1.2771,  1.5389,  1.6723,  1.1620, -0.3028])
tensor([2, 3, 3, 1, 3])


C:\Users\86151\AppData\Local\Temp\ipykernel_15144\1447715753.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Resize.cpp:37.)
  torch.max(x,0,False,out=p)


In [21]:
# 2-6
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])

TypeError: max() received an invalid combination of arguments - got (Tensor, int, bool, tuple), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, Tensor other, *, Tensor out = None)
      didn't match because some of the arguments have invalid types: (Tensor, !int!, !bool!, !tuple of (Tensor, Tensor)!)
 * (Tensor input, int dim, bool keepdim = False, *, tuple of Tensors out = None)
 * (Tensor input, name dim, bool keepdim = False, *, tuple of Tensors out = None)


In [22]:
# 2-7
m, idx = torch.max(x,True)

TypeError: max() received an invalid combination of arguments - got (Tensor, bool), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, Tensor other, *, Tensor out = None)
 * (Tensor input, int dim, bool keepdim = False, *, tuple of Tensors out = None)
 * (Tensor input, name dim, bool keepdim = False, *, tuple of Tensors out = None)


In [ ]:
# 逐元素比较两个张量，返回每个位置上的较大值。
t = torch.max(x,y)
print(t)

tensor([[-0.5184,  1.7938, -0.0694,  0.5381, -1.1189],
        [-0.5438, -0.2866,  0.2463,  1.1620, -0.5645],
        [ 1.6185, -0.0455, -0.3182, -0.0081,  1.2430],
        [ 2.0331,  1.5389,  1.6723,  3.2280,  1.2893]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [ ]:
# 模型和输入数据不在同一个设备（device）上
model = torch.nn.Linear(5,1).to("cuda:0") # 模型放在GPU
x = torch.Tensor([1,2,3,4,5]).to("cpu") # 输入数据放在CPU
y = model(x)

AssertionError: Torch not compiled with CUDA enabled

In [25]:
# 修改方法：
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = torch.nn.Linear(5,1).to(device)
x = torch.Tensor([1,2,3,4,5]).float().to(device)
y = model(x)
y

tensor([0.1903], grad_fn=<ViewBackward0>)

In [ ]:
# 1. 如果model之前定义在cpu上 下面的还会错
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

AssertionError: Torch not compiled with CUDA enabled

In [27]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [ ]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1) # 交换张量两个指定维度
z = x + y
print(z.shape)

torch.Size([4, 5])


In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,224,224) # # batch size is 2048 太大
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


RuntimeError: ignored

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
# 输入（outs）：形状为 (N, C) 的 float 张量（如 float32），表示每个样本在 C 个类别上的 logits；
# 目标（labels）：形状为 (N,) 的 长整型（long / int64） 张量，表示每个样本的真实类别索引（0 到 C-1）。
outs = torch.randn(5,5) # float32
labels = torch.Tensor([1,2,3,4,0]) # 返回的是float32 
lossval = L(outs,labels) # 出错

RuntimeError: ignored

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long() # 修复：转换为long类型
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader: # DataLoader(shuffle=True) 会在每个 epoch 开始时 随机打乱索引顺序，所以访问顺序不是1 2 3 ... 52
  print(datapoint)

['T']
['E']
['j']
['i']
['J']
['U']
['h']
['K']
['g']
['u']
['z']
['R']
['e']
['O']
['X']
['o']
['N']
['r']
['n']
['p']
['w']
['V']
['G']
['y']
['f']
['l']
['L']
['S']
['I']
['v']
['x']
['W']
['k']
['F']
['Y']
['A']
['H']
['c']
['m']
['t']
['M']
['b']
['q']
['s']
['B']
['Z']
['d']
['Q']
['P']
['C']
['D']
['a']
